name: backend
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pyopenms=3.3.0
  - rdkit=2023.09.4
  - pandas
  - flask
  - flask-cors
  - numpy
  - matplotlib
  - plotly
  - gevent
  - kaleido
  - pillow
  - requests
  - pip
  - pip:
      - fpdf
      - tldextract
      - python-dateutil
      - charset-normalizer
      - urllib3
      - markupsafe
      - PySocks
      - zipp
      - zope.interface
      - zope.event
      - blinker
      - filelock
      - importlib-metadata
      - importlib-resources
      - narwhals
      - six
      - idna
      - click
      - colorama
      - fonttools
      - kiwisolver
      - pyparsing
      - packaging
      - requests-file
